# Environment
# -------------------------------------

dist: trusty
addons:
  chrome: stable
  firefox: latest
sudo: required

# Build
# -------------------------------------

language: node_js
node_js:
  - "10"

# Deployment
# -------------------------------------

deploy:
  provider: npm
  on:
    tags: true
    node: "10"
  api_key:
    secure: "AWYBpaNNWZ1pVrT15RrEwAUsz6tqxAIIxPBVt5swm2WyEAeiBLF7XFXw/g1jJsPtE//mRY5OszMny/NdoitIJBDsyDKUsP/qJFQVET1HBSu+0QJnoGmNnaq8/wnlZX17amNWEup6GK+kDcjUX0/FY+0ErOti8PHPBoQrQ7en0SEolraKhggfqZsgoAqtjGf3E0N8LB3vSL2cMXzV9mkVTyk6RbmfVJgQxt/9k+NLt/6EAfgC+QrIBTtWfS0XdwsTkvqxqnUNY+1lfsiuY0pZ+AR/IRJ2lgwsdNMFzIDKib1hvuSJlfrKrnfJzZTjfUs3nNIfyw9mCqcqjEs+pwOSs3mM9zoAIxC17K+LvFFBsX1RuToy1ToBs/cpX4+Dg6FupPCZFRZIOcNjPQsOiZ5JwTvvp9DkZ6o2TGY0Zw6RPvJQC817feuF5i5G0lE08141RrFDnR8mMEzsohBT+/5iaWOX8Kldv+L4LXYc6bWKw3z00Ikzt1BJjiEimjfpUvPYCpl4dUQYZawGgjzI4co+8QJP4G0aAOQSRTM/CNxpeVcNLioseRUp+1Bg5BrSG7M3VEXfkTqTM7vw/012EGH3LOMvTVuYqG0JYvmZiK1qEOKR3jNE8Au/Q6DhbiGeBJ36eNYkrR+pKTMGfLY5235woETu74TcObkf5oNVcyT/tLk="
  email: "lsphillips.mail@gmail.com"
