name: Build and Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'

jobs:

  build-and-test:

    name: Build and Test

    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install NodeJS
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

    runs-on: ubuntu-latest
